---
# Leaving this very generic
- name: Create route53 entry
  community.aws.route53:
    state: present
    zone: "{{ domain }}"
    record: "{{ prefix }}.{{ domain }}"
    type: CNAME
    ttl: 60
    value: "{{ ip_address }}"
